steps:

  # Get the secrets
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: bash
    args: ["-c", "for secret in $(gcloud secrets list --filter=REACT --format='value(NAME)'); do echo $secret=\"$(gcloud secrets versions access --secret=$secret latest)\" >> .env; done"]
    dir: client

  # Build the front image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA",
      "-t",  "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:latest",
      "--build-arg", "APP_SERVER_URL=${_APP_SERVER_URL}", "."
    ]
    dir: client

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}"]

options:
    dynamic_substitutions: true

substitutions:
    _REGISTRY: "registry-${_ENV}"
    _REGISTRY_URL: europe-west1-docker.pkg.dev
    _APP_SERVER_URL: "https://backend-${_ENV}-4rok5wopuq-ew.a.run.app"
    _COMPONENT: frontend

timeout: 1200s

