export const activatedLanguages = {
  0: {
    langueFr: "Français",
    langueLoc: "Français",
    langueCode: "fr",
    i18nCode: "fr",
    avancement: 1,
    avancementTrad: 0,
  },
  1: {
    langueFr: "Pachto",
    langueLoc: "پښتو",
    langueCode: "af",
    i18nCode: "ps",
    avancement: 1,
    avancementTrad: 0,
  },
  2: {
    langueFr: "Anglais",
    langueLoc: "English",
    langueCode: "gb",
    i18nCode: "en",
    avancement: 1,
    avancementTrad: 0,
  },
  3: {
    langueFr: "Persan/Dari",
    langueLoc: "فارسی/ دری",
    langueCode: "ir",
    i18nCode: "fa",
    avancement: 1,
    avancementTrad: 0,
  },
  4: {
    langueFr: "Tigrinya",
    langueLoc: "ትግርኛ",
    langueCode: "er",
    i18nCode: "ti-ER",
    avancement: 1,
    avancementTrad: 0,
  },
  5: {
    langueFr: "Russe",
    langueLoc: "Русский",
    langueCode: "ru",
    i18nCode: "ru",
    avancement: 1,
    avancementTrad: 0,
  },
  6: {
    langueFr: "Arabe",
    langueLoc: "العربية",
    langueCode: "sa",
    i18nCode: "ar",
    avancement: 1,
    avancementTrad: 0,
  },
};
