export const FETCH_SELECTED_DISPOSITIF = "FETCH_SELECTED_DISPOSITIF";
export const SET_SELECTED_DISPOSITIF = "SET_SELECTED_DISPOSITIF";
export const UPDATE_UI_ARRAY = "UPDATE_UI_ARRAY";
export const SET_UI_ARRAY = "SET_UI_ARRAY";
export const UPDATE_SELECTED_DISPOSITIF = "UPDATE_SELECTED_DISPOSITIF";
