export interface RegionData {
  department: string;
  region: string;
}

export const departmentRegionCorrespondency: RegionData[] = [
  { department: "1 - Ain", region: "Auvergne-Rhône-Alpes" },
  { department: "2 - Aisne", region: "Hauts-de-France" },
  { department: "3 - Allier", region: "Auvergne-Rhône-Alpes" },
  {
    department: "4 - Alpes-de-Haute-Provence",
    region: "Provence-Alpes-Côte d'Azur",
  },
  { department: "5 - Hautes-Alpes", region: "Provence-Alpes-Côte d'Azur" },
  { department: "6 - Alpes-Maritimes", region: "Provence-Alpes-Côte d'Azur" },
  { department: "7 - Ardèche", region: "Auvergne-Rhône-Alpes" },
  { department: "8 - Ardennes", region: "Grand Est" },
  { department: "9 - Ariège", region: "Occitanie" },
  { department: "10 - Aube", region: "Grand Est" },
  { department: "11 - Aude", region: "Occitanie" },
  { department: "12 - Aveyron", region: "Occitanie" },
  {
    department: "13 - Bouches-du-Rhône",
    region: "Provence-Alpes-Côte d'Azur",
  },
  { department: "14 - Calvados", region: "Normandie" },
  { department: "15 - Cantal", region: "Auvergne-Rhône-Alpes" },
  { department: "16 - Charente", region: "Nouvelle-Aquitaine" },
  { department: "17 - Charente-Maritime", region: "Nouvelle-Aquitaine" },
  { department: "18 - Cher", region: "Centre-Val de Loire" },
  { department: "19 - Corrèze", region: "Nouvelle-Aquitaine" },
  { department: "21 - Côte-d'Or", region: "Bourgogne-Franche-Comté" },
  { department: "22 - Côtes-d'Armor", region: "Bretagne" },
  { department: "23 - Creuse", region: "Nouvelle-Aquitaine" },
  { department: "24 - Dordogne", region: "Nouvelle-Aquitaine" },
  { department: "25 - Doubs", region: "Bourgogne-Franche-Comté" },
  { department: "26 - Drôme", region: "Auvergne-Rhône-Alpes" },
  { department: "27 - Eure", region: "Normandie" },
  { department: "28 - Eure-et-Loir", region: "Centre-Val de Loire" },
  { department: "29 - Finistère", region: "Bretagne" },
  { department: "2A - Corse-du-Sud", region: "Corse" },
  { department: "2B - Haute-Corse", region: "Corse" },
  { department: "30 - Gard", region: "Occitanie" },
  { department: "31 - Haute-Garonne", region: "Occitanie" },
  { department: "32 - Gers", region: "Occitanie" },
  { department: "33 - Gironde", region: "Nouvelle-Aquitaine" },
  { department: "34 - Hérault", region: "Occitanie" },
  { department: "35 - Ille-et-Vilaine", region: "Bretagne" },
  { department: "36 - Indre", region: "Centre-Val de Loire" },
  { department: "37 - Indre-et-Loire", region: "Centre-Val de Loire" },
  { department: "38 - Isère", region: "Auvergne-Rhône-Alpes" },
  { department: "39 - Jura", region: "Bourgogne-Franche-Comté" },
  { department: "40 - Landes", region: "Nouvelle-Aquitaine" },
  { department: "41 - Loir-et-Cher", region: "Centre-Val de Loire" },
  { department: "42 - Loire", region: "Auvergne-Rhône-Alpes" },
  { department: "43 - Haute-Loire", region: "Auvergne-Rhône-Alpes" },
  { department: "44 - Loire-Atlantique", region: "Pays de la Loire" },
  { department: "45 - Loiret", region: "Centre-Val de Loire" },
  { department: "46 - Lot", region: "Occitanie" },
  { department: "47 - Lot-et-Garonne", region: "Nouvelle-Aquitaine" },
  { department: "48 - Lozère", region: "Occitanie" },
  { department: "49 - Maine-et-Loire", region: "Pays de la Loire" },
  { department: "50 - Manche", region: "Normandie" },
  { department: "51 - Marne", region: "Grand Est" },
  { department: "52 - Haute-Marne", region: "Grand Est" },
  { department: "53 - Mayenne", region: "Pays de la Loire" },
  { department: "54 - Meurthe-et-Moselle", region: "Grand Est" },
  { department: "55 - Meuse", region: "Grand Est" },
  { department: "56 - Morbihan", region: "Bretagne" },
  { department: "57 - Moselle", region: "Grand Est" },
  { department: "58 - Nièvre", region: "Bourgogne-Franche-Comté" },
  { department: "59 - Nord", region: "Hauts-de-France" },
  { department: "60 - Oise", region: "Hauts-de-France" },
  { department: "61 - Orne", region: "Normandie" },
  { department: "62 - Pas-de-Calais", region: "Hauts-de-France" },
  { department: "63 - Puy-de-Dôme", region: "Auvergne-Rhône-Alpes" },
  { department: "64 - Pyrénées-Atlantiques", region: "Nouvelle-Aquitaine" },
  { department: "65 - Hautes-Pyrénées", region: "Occitanie" },
  { department: "66 - Pyrénées-Orientales", region: "Occitanie" },
  { department: "67 - Bas-Rhin", region: "Grand Est" },
  { department: "68 - Haut-Rhin", region: "Grand Est" },
  { department: "69 - Rhône", region: "Auvergne-Rhône-Alpes" },
  { department: "70 - Haute-Saône", region: "Bourgogne-Franche-Comté" },
  { department: "71 - Saône-et-Loire", region: "Bourgogne-Franche-Comté" },
  { department: "72 - Sarthe", region: "Pays de la Loire" },
  { department: "73 - Savoie", region: "Auvergne-Rhône-Alpes" },
  { department: "74 - Haute-Savoie", region: "Auvergne-Rhône-Alpes" },
  { department: "75 - Paris", region: "Île-de-France" },
  { department: "76 - Seine-Maritime", region: "Normandie" },
  { department: "77 - Seine-et-Marne", region: "Île-de-France" },
  { department: "78 - Yvelines", region: "Île-de-France" },
  { department: "79 - Deux-Sèvres", region: "Nouvelle-Aquitaine" },
  { department: "80 - Somme", region: "Hauts-de-France" },
  { department: "81 - Tarn", region: "Occitanie" },
  { department: "82 - Tarn-et-Garonne", region: "Occitanie" },
  { department: "83 - Var", region: "Provence-Alpes-Côte d'Azur" },
  { department: "84 - Vaucluse", region: "Provence-Alpes-Côte d'Azur" },
  { department: "85 - Vendée", region: "Pays de la Loire" },
  { department: "86 - Vienne", region: "Nouvelle-Aquitaine" },
  { department: "87 - Haute-Vienne", region: "Nouvelle-Aquitaine" },
  { department: "88 - Vosges", region: "Grand Est" },
  { department: "89 - Yonne", region: "Bourgogne-Franche-Comté" },
  {
    department: "90 - Territoire de Belfort",
    region: "Bourgogne-Franche-Comté",
  },
  { department: "91 - Essonne", region: "Île-de-France" },
  { department: "92 - Hauts-de-Seine", region: "Île-de-France" },
  { department: "93 - Seine-Saint-Denis", region: "Île-de-France" },
  { department: "94 - Val-de-Marne", region: "Île-de-France" },
  { department: "95 - Val-d'Oise", region: "Île-de-France" },
];
