import { AlgoliaObject } from "../../types/interface";

export const indexableTags: AlgoliaObject[] = [
  {
    "objectID": "Français",
    "title_fr": "Français",
    "name_fr": "apprendre le français",
    "title_en": "French",
    "title_ar": "الفرنسيّة",
    "title_fa": "فرانسوی",
    "title_ps": "فرانسوی",
    "title_ru": "Французский",
    "title_ti-ER": "ፈረንሳይ",
    "name_en": "learn French",
    "name_ar": "تعلّم الفرنسيّة",
    "name_fa": "آموختن زبان فرانسوی",
    "name_ps": "فرانسوي زده کړئ",
    "name_ru": "учить французский",
    "name_ti-ER": "ትምህርቲ ቓንቓ ፈርንሳይ ምምሃር",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Administratif",
    "title_fr": "Administratif",
    "name_fr": "gérer mes papiers",
    "title_en": "Admin",
    "title_ar": "المعاملات الاداريّة",
    "title_fa": "اداری",
    "title_ps": "اداري",
    "title_ru": "Административное",
    "title_ti-ER": "ቤት ጽሕፈታት",
    "name_en": "manage my paperwork",
    "name_ar": "إدارة أوراقي",
    "name_fa": "مدیریت پرونده هایم",
    "name_ps": "خپلې اسناد تنظیم کړئ",
    "name_ru": "разобраться с документами",
    "name_ti-ER": "ባዕለይ የሳልጥ  ወረቃቕተይ",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Logement",
    "title_fr": "Logement",
    "name_fr": "me loger",
    "title_en": "Housing",
    "title_ar": "إسكان",
    "title_fa": "مسکن",
    "title_ps": "استوګنځای",
    "title_ru": "Жилье",
    "title_ti-ER": "መንበሪ ገዛ",
    "name_en": "find housing",
    "name_ar": "إيجاد سكن",
    "name_fa": "پیدا کردن جای سکونت",
    "name_ps": "استوګنځای پیداکړئ",
    "name_ru": "найти жилье",
    "name_ti-ER": "ክነብር",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Mobilité",
    "title_fr": "Mobilité",
    "name_fr": "me déplacer",
    "title_en": "Mobility",
    "title_ar": "التنقّل",
    "title_fa": "تحرک",
    "title_ps": "خوځښت",
    "title_ru": "Мобильность",
    "title_ti-ER": "ብቅዓት = ክእለት",
    "name_en": "move about",
    "name_ar": "التنقّل",
    "name_fa": "سفر کردن",
    "name_ps": "تقل او حرکت",
    "name_ru": "перемещаться",
    "name_ti-ER": "ኣነ ክሳፈር \\ ይጉዓዝ",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Insertion pro",
    "title_fr": "Insertion pro",
    "name_fr": "trouver un travail",
    "title_en": "Job hunting",
    "title_ar": "الاندماج المهني",
    "title_fa": "درج حرفه ای",
    "title_ps": "مسلکي مرسته",
    "title_ru": "Работа",
    "title_ti-ER": "ምትእትታው ሞያ ብውሕልልነት",
    "name_en": "find a job",
    "name_ar": "ايجاد عمل",
    "name_fa": "پیدا کردن شغل",
    "name_ps": "دنده ومومئ",
    "name_ru": "найти работу",
    "name_ti-ER": "ሓደ ስራሕ ምርካብ",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Santé",
    "title_fr": "Santé",
    "name_fr": "me soigner",
    "title_en": "Health",
    "title_ar": "الصحّة",
    "title_fa": "صحت",
    "title_ps": "روغتیا",
    "title_ru": "Здоровье",
    "title_ti-ER": "ጥዕና",
    "name_en": "get medical care",
    "name_ar": "العناية الصحّية",
    "name_fa": "درمان",
    "name_ps": "خپله درملنه وکړئ",
    "name_ru": "получить медицинскую помощь",
    "name_ti-ER": "ኣነ ክሕከም",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Formation pro",
    "title_fr": "Formation pro",
    "name_fr": "apprendre un métier",
    "title_en": "Professional training",
    "title_ar": "التدريب المهني",
    "title_fa": "آموزش حرفه ای",
    "title_ps": "مسلکي روزنه",
    "title_ru": "Профессиональная подготовка",
    "title_ti-ER": "ምስልጣን ሞያ",
    "name_en": "learn a job",
    "name_ar": "تعلم مهنة",
    "name_fa": "آموختن یک کسب",
    "name_ps": "یو کسب زده کړئ",
    "name_ru": "получить профессию",
    "name_ti-ER": "ሓደ ሞያ ምምሃር",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Études",
    "title_fr": "Études",
    "name_fr": "faire des études",
    "title_en": "Studies",
    "title_ar": "الدّراسة",
    "title_fa": "تحصیلات",
    "title_ps": "زده کړې",
    "title_ru": "Учеба",
    "title_ti-ER": "ምምሃር",
    "name_en": "study",
    "name_ar": "الدّراسة",
    "name_fa": "شروع کردن تحصیل",
    "name_ps": "زده کړې ترسره کړئ",
    "name_ru": "учиться",
    "name_ti-ER": "ትምህርቲ ምግባር",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Bénévolat",
    "title_fr": "Bénévolat",
    "name_fr": "aider une association",
    "title_en": "Volunteering",
    "title_ar": "التطوع",
    "title_fa": "داوطلب",
    "title_ps": "داوطلب",
    "title_ru": "Волонтерство",
    "title_ti-ER": "ወልንታዊ",
    "name_en": "help an association",
    "name_ar": "مساعدة جمعية",
    "name_fa": "کمک انجمن",
    "name_ps": "یوې ټولنې سره مرسته وکړئ",
    "name_ru": "стать волонтером",
    "name_ti-ER": "ሓገዝ ንሓንቲ ማሕበር",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Rencontre",
    "title_fr": "Rencontre",
    "name_fr": "rencontrer des gens",
    "title_en": "Socialising",
    "title_ar": "لقاء الآخرين",
    "title_fa": "ملاقات",
    "title_ps": "لیدنه",
    "title_ru": "Общение",
    "title_ti-ER": "ምርኻብ ወይ ምዝታይ",
    "name_en": "meet people",
    "name_ar": "مقابلة أشخاص",
    "name_fa": "تماس شدن با مردم",
    "name_ps": "خلکو سره ووینئ",
    "name_ru": "познакомиться с людьми",
    "name_ti-ER": "ምስ ደቂ ሰባት ምርኻብ",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Loisir",
    "title_fr": "Loisir",
    "name_fr": "occuper mon temps libre",
    "title_en": "Leisure",
    "title_ar": "التّسلية",
    "title_fa": "سرگرمی ها",
    "title_ps": "تفریح",
    "title_ru": "Досуг",
    "title_ti-ER": "ምዝንጋዕ",
    "name_en": "occupy my free time",
    "name_ar": "إشغال وقت فراغي",
    "name_fa": "مشغول شدن در اوقات بیکار",
    "name_ps": "خپل اضافی او فارغ وخت ډک کړئ",
    "name_ru": "занять свободное время",
    "name_ti-ER": "ኣብ ትርፊ ግዘይ መደብ ምሓዝ",
    "typeContenu": "theme",
    "priority": 10
  },
  {
    "objectID": "Culture",
    "title_fr": "Culture",
    "name_fr": "découvrir la culture",
    "title_en": "Culture",
    "title_ar": "الثقافة",
    "title_fa": "فرهنگ",
    "title_ps": "کلتور",
    "title_ru": "Культура",
    "title_ti-ER": "ባህሊ",
    "name_en": "discover French culture",
    "name_ar": "اكتشاف الثقافة",
    "name_fa": "اشناشدن با فرهنگ",
    "name_ps": "د کلتور په اړه پوهاوی ترلاسه کړئ",
    "name_ru": "узнать о культуре",
    "name_ti-ER": "ሓድሽ ባህሊ ምልላይ",
    "typeContenu": "theme",
    "priority": 10
  }
]
