export const themes = {
  Santé: [
    "malade",
    "maladie",
    "psy",
    "soin",
    "médecin",
    "docteur",
    "parcours de soin",
    "cmu-c",
    "cmu",
    "puma",
    "psychiatrie",
    "psychologie",
    "hôpital",
    "clinique",
    "médicament",
    "comprimé",
    "soigner",
    "médical",
    "samté",
    "senté",
    "semté",
    "sécu",
    "enceinte",
    "covid",
    "coronavirus",
  ],
  Administratif: [
    "papiers",
    "administratif",
    "préfecture",
    "titre de séjour",
    "carte de séjour",
    "séjour",
    "état civil",
    "RSA",
    "cmu-c",
    "cmu",
    "navigo",
    "permis de conduire",
    "acte de naissance",
    "acte de mariage",
    "acte de décès",
    "ofpra",
    "cnda",
    "ofii",
    "caf",
    "cnam",
    "récépissé",
    "attestation",
    "justificatif",
    "logement social",
    "demande",
    "allocation",
    "carte de crédit",
    "banque",
  ],
  Rencontre: [
    "amis",
    "sortir",
    "rencontrer",
    "discuter",
    "parler",
    "apéro",
    "dîner",
    "déjeuner",
    "echange",
    "français",
    "soirée",
    "apprendre",
    "découvrir",
    "parrainage",
    "parrain",
  ],
  Bénévolat: [
    "aider",
    "bénévole",
    "engager",
    "s'engager",
    "solidarité",
    "partager",
    "volonteer",
    "association",
    "service civique",
  ],
  Logement: [
    "maison",
    "appartement",
    "foyer",
    "centre d'hébergement",
    "hébergement",
    "me loger",
    "dormir",
    "sdf",
    "rue",
    "colocation",
    "logement social",
    "studio",
    "loyer",
    "cph",
    "cada",
    "huda",
    "cao",
    "habiter",
    "habitation",
    "chez soi",
  ],
  Français: [
    "parler",
    "écrire",
    "français",
    "cecrl",
    "A1",
    "A2",
    "B1",
    "B2",
    "C1",
    "C2",
    "FLE",
    "cours",
    "apprendre français",
    "atelier linguistique",
    "méthode d'auto-apprentissage",
    "auto apprentissage",
    "école",
    "langue",
    "french",
    "lire",
    "tutorat",
    "tuteur",
    "prononcer",
    "prononciation",
    "progresser",
  ],
  Études: [
    "étudier",
    "école",
    "université",
    "apprendre",
    "sorbonne",
    "bac",
    "lycée",
    "collège",
    "maternelle",
    "examens",
    "licence",
    "master",
    "diplôme",
    "équivalence",
    "universitaire",
    "fac",
    "grande école",
    "cours",
    "éducation",
    "formation continue",
    "formation initiale",
    "DU passerelle",
    "CROUS",
    "bourses",
    "reprise",
    "inscription",
  ],
  "Formation pro": [
    "me former",
    "apprendre",
    "métier",
    "CAP",
    "BTS",
    "chantier",
    "BTP",
    "apprentissage",
    "CFA",
    "pôle emploi",
    "mission locale",
    "cap emploi",
    "apec",
    "hope",
    "geiq",
    "alternance",
  ],
  "Insertion pro": [
    "travail",
    "emploi",
    "travailler",
    "pôle",
    "pole emploi",
    "recherche d'emploi",
    "trouver travail",
    "métier",
    "mission locale",
    "cap emploi",
    "apec",
    "salaire",
    "rémunération",
    "chômage",
    "chomage",
    "indemnisation",
    "allocation",
    "rsa",
  ],
  Culture: [
    "cinema",
    "me cultiver",
    "art",
    "histoire",
    "musée",
    "film",
    "musique",
    "concert",
    "spectacle",
    "salle",
    "peinture",
    "sculpture",
    "gravure",
    "découvrir",
    "éducation",
    "pratique artistique",
    "instruments de musique",
    "jouer",
    "sortir",
    "découvrir",
    "visiter",
  ],
  Loisir: [
    "sport",
    "football",
    "cuisine",
    "activité",
    "passion",
    "hobby",
    "temps libre",
    "rugby",
    "équipe",
    "jouer",
    "musique",
  ],
  Mobilité: [
    "transport",
    "voiture",
    "train",
    "bus",
    "déplacement",
    "rer",
    "metro",
    "tram",
    "permis",
    "conduire",
    "code",
    "licence",
    "ticket",
    "vélo",
    "velo",
  ],
};
