export const fr = {
  Santé: [
    "malade",
    "maladie",
    "psy",
    "soin",
    "médecin",
    "docteur",
    "parcours de soin",
    "cmu-c",
    "cmu",
    "puma",
    "psychiatrie",
    "psychologie",
    "hôpital",
    "clinique",
    "médicament",
    "comprimé",
    "soigner",
    "médical",
    "samté",
    "senté",
    "semté",
    "sécu",
    "enceinte",
    "covid",
    "coronavirus",
    "santé",
    "me soigner",
  ],
  Administratif: [
    "papiers",
    "administratif",
    "préfecture",
    "titre de séjour",
    "carte de séjour",
    "séjour",
    "état civil",
    "RSA",
    "cmu-c",
    "cmu",
    "navigo",
    "permis de conduire",
    "acte de naissance",
    "acte de mariage",
    "acte de décès",
    "ofpra",
    "cnda",
    "ofii",
    "caf",
    "cnam",
    "récépissé",
    "attestation",
    "justificatif",
    "logement social",
    "demande",
    "allocation",
    "carte de crédit",
    "banque",
    "gérer mes papiers",
  ],
  Rencontre: [
    "amis",
    "sortir",
    "rencontrer",
    "discuter",
    "parler",
    "apéro",
    "dîner",
    "déjeuner",
    "echange",
    "français",
    "soirée",
    "apprendre",
    "découvrir",
    "parrainage",
    "parrain",
    "rencontrer des gens",
  ],
  Bénévolat: [
    "aider",
    "bénévole",
    "engager",
    "s'engager",
    "solidarité",
    "partager",
    "volonteer",
    "association",
    "service civique",
    "bénévolat",
    "aider une association",
  ],
  Logement: [
    "maison",
    "appartement",
    "foyer",
    "centre d'hébergement",
    "hébergement",
    "me loger",
    "dormir",
    "sdf",
    "rue",
    "colocation",
    "logement social",
    "studio",
    "loyer",
    "cph",
    "cada",
    "huda",
    "cao",
    "habiter",
    "habitation",
    "chez soi",
  ],
  Français: [
    "parler",
    "écrire",
    "français",
    "cecrl",
    "A1",
    "A2",
    "B1",
    "B2",
    "C1",
    "C2",
    "FLE",
    "cours",
    "apprendre français",
    "atelier linguistique",
    "méthode d'auto-apprentissage",
    "auto apprentissage",
    "école",
    "langue",
    "french",
    "lire",
    "tutorat",
    "tuteur",
    "prononcer",
    "prononciation",
    "progresser",
    "apprendre le français",
  ],
  Études: [
    "étudier",
    "école",
    "université",
    "apprendre",
    "sorbonne",
    "bac",
    "lycée",
    "collège",
    "maternelle",
    "examens",
    "licence",
    "master",
    "diplôme",
    "équivalence",
    "universitaire",
    "fac",
    "grande école",
    "cours",
    "éducation",
    "formation continue",
    "formation initiale",
    "DU passerelle",
    "CROUS",
    "bourses",
    "reprise",
    "inscription",
    "faire des études",
    "études",
  ],
  "Formation pro": [
    "me former",
    "apprendre un métier",
    "métier",
    "CAP",
    "BTS",
    "chantier",
    "BTP",
    "apprentissage",
    "CFA",
    "pôle emploi",
    "mission locale",
    "cap emploi",
    "apec",
    "hope",
    "geiq",
    "alternance",
    "formation professionnelle",
  ],
  "Insertion pro": [
    "travail",
    "emploi",
    "travailler",
    "pôle",
    "pole emploi",
    "recherche d'emploi",
    "trouver travail",
    "métier",
    "mission locale",
    "cap emploi",
    "apec",
    "salaire",
    "rémunération",
    "chômage",
    "chomage",
    "indemnisation",
    "allocation",
    "rsa",
    "insertion professionnelle",
    "trouver un travail",
  ],
  Culture: [
    "cinema",
    "me cultiver",
    "art",
    "histoire",
    "musée",
    "film",
    "musique",
    "concert",
    "spectacle",
    "salle",
    "peinture",
    "sculpture",
    "gravure",
    "découvrir",
    "éducation",
    "pratique artistique",
    "instruments de musique",
    "jouer",
    "sortir",
    "découvrir",
    "visiter",
    "culture",
    "découvrir la culture",
  ],
  Loisir: [
    "sport",
    "football",
    "cuisine",
    "activité",
    "passion",
    "hobby",
    "temps libre",
    "rugby",
    "équipe",
    "jouer",
    "musique",
    "loisir",
    "occuper mon temps libre",
  ],
  Mobilité: [
    "transport",
    "voiture",
    "train",
    "bus",
    "déplacement",
    "rer",
    "metro",
    "tram",
    "permis",
    "conduire",
    "code",
    "licence",
    "ticket",
    "vélo",
    "velo",
    "mobilité",
    "me déplacer",
  ],
};

export const ru = {
  Santé: [
    "cmu",
    "cmu-c",
    "coronavirus",
    "puma",
    "sécu",
    "амели",
    "анализы",
    "аптека",
    "беременная",
    "беременность",
    "болезнь",
    "больница",
    "больной",
    "болею",
    "в положении",
    "вирус",
    "врач",
    "вызвать врача",
    "выздороветь",
    "вылечить",
    "госпиталь",
    "доктор",
    "заболевание",
    "зубной",
    "инвалид",
    "инвалидность",
    "клиника",
    "ковид",
    "корона covid",
    "коронавирус",
    "лекарства",
    "лекарственные препараты",
    "лекарство",
    "мед помощь",
    "медецинская помощь",
    "медик",
    "медикаменты",
    "медицинская",
    "медицинский",
    "медицинский уход",
    "медицинское",
    "осмотр врача",
    "поликлинника",
    "помош врача",
    "помощь врача",
    "прием врача",
    "припадок",
    "простуда",
    "психиатр",
    "психотерапевт",
    "ранение",
    "рецепт на лекарства",
    "секю",
    "страховка",
    "таблетки",
    "терапевт",
    "терапия",
    "травма",
    "универсальная страховка",
  ],
  Administratif: [
    "RSA",
    "caf",
    "cmu",
    "cmu-c",
    "cnam",
    "cnda",
    "navigo",
    "ofii",
    "ofpra",
    "административная",
    "административный",
    "аусвайс",
    "аушвайс",
    "банк",
    "банковская карта",
    "брак",
    "водительские",
    "водительское",
    "гражданство",
    "документы",
    "запрос",
    "зарегистрироваться",
    "карт де",
    "каф",
    "навиго",
    "офии",
    "офпра",
    "оффи",
    "подтверждение",
    "получить карту",
    "получить номер страховки",
    "получить страховку",
    "поменять прова",
    "пособие",
    "права на вождение",
    "префектура",
    "проездной документ",
    "ресеписе",
    "рса",
    "свадьба",
    "свидетельство",
    "свидетельство о рождении",
    "свидетельство о смерти",
    "сежур",
    "сижур",
    "снам",
    "снда",
    "социальное жилье",
    "справка",
    "титр",
  ],
  Rencontre: [
    "аперитив",
    "вечер",
    "включиться в общество",
    "встречаться",
    "говорить",
    "гулять",
    "друзья",
    "дружеский",
    "интересы",
    "интересам",
    "ищу друзей",
    "компания",
    "клуб",
    "местные друзья",
    "найти друзей",
    "обед",
    "обмен",
    "общаться",
    "общество",
    "открыть",
    "подруги",
    "познакомиться",
    "практика языка",
    "ужин",
    "узнать",
    "французский",
    "хобби",
    "хочу общаться",
  ],
  Bénévolat: [
    "беневоль",
    "волонтер",
    "волонтером",
    "волонтерство",
    "волонтерствовать",
    "волонтерством",
    "гражданская служба",
    "делиться",
    "сервис сивик",
    "солидарность",
    "помогать",
    "участие в ассоциации",
  ],
  Logement: [
    "cada",
    "cao",
    "cph",
    "huda",
    "аренда",
    "бездомный",
    "временное жилье",
    "дом",
    "жилье",
    "жить",
    "када",
    "квартира",
    "комната",
    "кров",
    "на улице",
    "переночевать",
    "поселиться",
    "снять",
    "соседство",
    "социальное жилье",
    "спать",
    "студия",
    "фойе",
    "центр размещения",
    "юда",
    "115",
  ],
  Français: [
    "A1",
    "A2",
    "B1",
    "B2",
    "C1",
    "C2",
    "FLE",
    "cecrl",
    "выучить",
    "выучить французский",
    "говорить",
    "изучать язык",
    "курс",
    "лингвистический семинар",
    "метод самообучения",
    "научиться",
    "освоить",
    "писать",
    "прогресс",
    "произносить",
    "произношение",
    "репетитор",
    "репетиторство",
    "самообучение",
    "сертификат язык",
    "уметь говорить",
    "французский",
    "французском",
    "читать",
    "школа",
    "язык",
    "языка",
    "языковой",
    "языковые",
    "экзамен",
  ],
  Études: [
    "bac",
    "DU",
    "crous",
    "passerelle",
    "sorbona",
    "sorbonna",
    "sorbonnе",
    "бак",
    "бакалавр",
    "высшая школа",
    "детский сад",
    "диплом",
    "запись в университет",
    "зачисление",
    "колледж",
    "крус",
    "курсы",
    "лицей",
    "лисанс",
    "магистр",
    "начальное образование",
    "образование",
    "получить стипендию",
    "поступить",
    "продолжить учебу",
    "промежуточная учеба",
    "резюме",
    "сарбона",
    "сессия",
    "соответствие диплома",
    "сорбона",
    "сорбонна",
    "стипендии",
    "стипендия",
    "универ",
    "университет",
    "университет",
    "учеба",
    "учиться",
    "учиться со стипендией",
    "школа",
    "школа",
    "эквивалент",
    "эквивалентность",
    "экзамены",
  ],
  "Formation pro": [
    "BTS",
    "CAP",
    "CFA",
    "cap",
    "apec",
    "geiq",
    "hope",
    "pole emploi",
    "альтернанс",
    "апек",
    "выучиться на ",
    "местная миссия",
    "получить профессию",
    "продавец",
    "поль амплуа",
    "поль имлуа",
    "проф обучение",
    "профессиональные курсы",
    "профессия",
    "проф курсы",
    "ремесло",
    "строительство",
    "стройка",
    "трудоустроиться",
    "центр занятости",
    "чередование",
  ],
  "Insertion pro": [
    "apec",
    "cap",
    "chomage",
    "rsa",
    "апек",
    "безработица",
    "временная работа",
    "зарплата",
    "интерим",
    "ищу работу",
    "компенсация",
    "местная миссия",
    "найти работу",
    "поиск работы",
    "поль",
    "поль амплуа",
    "поль имплуа",
    "пособие",
    "работа",
    "работа контракт",
    "работать",
    "ремесло",
    "труд",
    "трудоустроиться",
    "трудоустройство",
    "устроиться",
    "хочу работать",
    "центр труда",
    "центр трудоустройства",
    "шамаж",
    "шомаж",
  ],
  Culture: [
    "гравюра",
    "живопись",
    "зал",
    "заняться",
    "играть",
    "искусство",
    "история",
    "картина",
    "кино",
    "концерт",
    "культура",
    "музей",
    "музыка",
    "музыкальнай инструмент",
    "музыкальные инструменты",
    "образование",
    "окультуриться",
    "открыть для себя",
    "погулять",
    "посетить",
    "поход",
    "рисовать",
    "скульптура",
    "сходить",
    "узнать новое",
    "художественная практика",
    "шоу",
    "экскурсия",
  ],
  Loisir: [
    "деятельность",
    "играть",
    "команда",
    "кулинария",
    "музыка",
    "регби",
    "свободное время",
    "спорт",
    "футбол",
    "увлечение",
    "хобби",
  ],
  Mobilité: [
    "rer",
    "автобус",
    "автомобиль",
    "билет",
    "велик",
    "вело",
    "велосипед",
    "добраться",
    "ездить",
    "лицензия",
    "лицензия",
    "машина",
    "метро",
    "пдд",
    "перемещение",
    "поезд",
    "правила дорожного движения",
    "рер",
    "трамвай",
    "транспорт",
    "экспресс",
    "электричка",
  ],
};

export const en = {
  Santé: [
    "health","sick","doctor","get medical care"
  ],
  Administratif: [
    "admin","manage my paperwork"
  ],
  Rencontre: [
    "socializing","meet people"
  ],
  Bénévolat: [
    "volunteering","help an association"
  ],
  Logement: [
    "housing","find housing"
  ],
  Français: [
    "french","learn french"
  ],
  Études: [
    "studies","study"
  ],
  "Formation pro": [
    "professional training","learn a job"
  ],
  "Insertion pro": [
    "job hunting","find a job","work","find a work"
  ],
  Culture: [
    "culture","discover French culture"
  ],
  Loisir: [
    "leisure","occupy my free time"
  ],
  Mobilité: [
    "transportation","use transportation"
  ],
};
