steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA"
      - "-t"
      - "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:latest"
      - "-f"
      - "./apps/server/Dockerfile"
      - "."
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA"
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        # Use array for optional command-line arguments (Google Shell Style Guide)
        # https://google.github.io/styleguide/shellguide.html#arrays
        vpc_args=()
        if [[ -n "${_VPC_CONNECTOR}" ]]; then
          vpc_args=(--vpc-connector="${_VPC_CONNECTOR}")
        fi

        gcloud run deploy ${_COMPONENT}-${_ENV} \
          --allow-unauthenticated \
          --image ${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA \
          --max-instances ${_MAX_INSTANCES} \
          --memory ${_MEMORY} \
          --platform managed \
          --project ${_PROJECT_NAME} \
          --region ${_REGION} \
          --service-account ${_SA} \
          --set-env-vars accountSid=sm://refugies-info/accountSid \
          --set-env-vars AIRTABLE_BASE_CONTENU=sm://refugies-info/${_AIRTABLE_BASE_CONTENU_VAR} \
          --set-env-vars AIRTABLE_BASE_TRAD=sm://refugies-info/${_AIRTABLE_BASE_TRAD_VAR} \
          --set-env-vars AIRTABLE_BASE_USERS=sm://refugies-info/AIRTABLE_BASE_USERS \
          --set-env-vars AIRTABLE_TOKEN=sm://refugies-info/AIRTABLE_TOKEN \
          --set-env-vars ALGOLIA_API_KEY=sm://refugies-info/ALGOLIA_API_KEY \
          --set-env-vars ALGOLIA_INDEX=sm://refugies-info/${_ALGOLIA_INDEX_VAR} \
          --set-env-vars API_KEY=sm://refugies-info/API_KEY \
          --set-env-vars API_SECRET=sm://refugies-info/API_SECRET \
          --set-env-vars authToken=sm://refugies-info/authToken \
          --set-env-vars BREVO_API_KEY=sm://refugies-info/BREVO_API_KEY \
          --set-env-vars CLOUD_NAME=sm://refugies-info/CLOUD_NAME \
          --set-env-vars CRON_TOKEN=sm://refugies-info/CRON_TOKEN \
          --set-env-vars EXPO_ACCESS_TOKEN=sm://refugies-info/EXPO_ACCESS_TOKEN \
          --set-env-vars FRONT_SITE_URL=sm://refugies-info/${_FRONT_URL_VAR} \
          --set-env-vars GCLOUD_CLIENT_EMAIL=sm://refugies-info/GCLOUD_CLIENT_EMAIL \
          --set-env-vars GCLOUD_CLIENT_ID=sm://refugies-info/GCLOUD_CLIENT_ID \
          --set-env-vars GCLOUD_CLIENT_X509=sm://refugies-info/GCLOUD_CLIENT_X509 \
          --set-env-vars GCLOUD_PKEY=sm://refugies-info/GCLOUD_PKEY \
          --set-env-vars GCLOUD_PRIVATE_KEY_ID=sm://refugies-info/GCLOUD_PRIVATE_KEY_ID \
          --set-env-vars GOOGLE_CLIENT_ID=sm://refugies-info/GOOGLE_CLIENT_ID \
          --set-env-vars GOOGLE_CLIENT_SECRET=sm://refugies-info/GOOGLE_CLIENT_SECRET \
          --set-env-vars MICROSOFT_CLIENT_ID=sm://refugies-info/MICROSOFT_CLIENT_ID \
          --set-env-vars MICROSOFT_CLIENT_SECRET=sm://refugies-info/MICROSOFT_CLIENT_SECRET \
          --set-env-vars MINIMUM_APP_VERSION=${_MINIMUM_APP_VERSION} \
          --set-env-vars MONGODB_URI=sm://refugies-info/${_MONGODB_VAR} \
          --set-env-vars NODE_ENV=${_NODE_ENV} \
          --set-env-vars POSTMAN_SECRET=sm://refugies-info/POSTMAN_SECRET \
          --set-env-vars REACT_APP_SITE_SECRET=sm://refugies-info/REACT_APP_SITE_SECRET \
          --set-env-vars SECRET=sm://refugies-info/SECRET \
          --set-env-vars SENDGRID_API_KEY=sm://refugies-info/SENDGRID_API_KEY \
          --set-env-vars SLACK_WEBHOOK_URL=sm://refugies-info/SLACK_WEBHOOK_URL \
          --set-env-vars SMS_SENDER=sm://refugies-info/SMS_SENDER \
          --set-env-vars TTS_KEY_1=sm://refugies-info/TTS_KEY_1 \
          "${vpc_args[@]}"

substitutions:
  _MAX_INSTANCES: "20"

options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_8"
