export const departmentRegionCorrespondency = [
  { departement: "1 - Ain", region: "Auvergne-Rhône-Alpes" },
  { departement: "2 - Aisne", region: "Hauts-de-France" },
  { departement: "3 - Allier", region: "Auvergne-Rhône-Alpes" },
  {
    departement: "4 - Alpes-de-Haute-Provence",
    region: "Provence-Alpes-Côte d'Azur",
  },
  { departement: "5 - Hautes-Alpes", region: "Provence-Alpes-Côte d'Azur" },
  { departement: "6 - Alpes-Maritimes", region: "Provence-Alpes-Côte d'Azur" },
  { departement: "7 - Ardèche", region: "Auvergne-Rhône-Alpes" },
  { departement: "8 - Ardennes", region: "Grand Est" },
  { departement: "9 - Ariège", region: "Occitanie" },
  { departement: "10 - Aube", region: "Grand Est" },
  { departement: "11 - Aude", region: "Occitanie" },
  { departement: "12 - Aveyron", region: "Occitanie" },
  {
    departement: "13 - Bouches-du-Rhône",
    region: "Provence-Alpes-Côte d'Azur",
  },
  { departement: "14 - Calvados", region: "Normandie" },
  { departement: "15 - Cantal", region: "Auvergne-Rhône-Alpes" },
  { departement: "16 - Charente", region: "Nouvelle-Aquitaine" },
  { departement: "17 - Charente-Maritime", region: "Nouvelle-Aquitaine" },
  { departement: "18 - Cher", region: "Centre-Val de Loire" },
  { departement: "19 - Corrèze", region: "Nouvelle-Aquitaine" },
  { departement: "21 - Côte-d'Or", region: "Bourgogne-Franche-Comté" },
  { departement: "22 - Côtes-d'Armor", region: "Bretagne" },
  { departement: "23 - Creuse", region: "Nouvelle-Aquitaine" },
  { departement: "24 - Dordogne", region: "Nouvelle-Aquitaine" },
  { departement: "25 - Doubs", region: "Bourgogne-Franche-Comté" },
  { departement: "26 - Drôme", region: "Auvergne-Rhône-Alpes" },
  { departement: "27 - Eure", region: "Normandie" },
  { departement: "28 - Eure-et-Loir", region: "Centre-Val de Loire" },
  { departement: "29 - Finistère", region: "Bretagne" },
  { departement: "2A - Corse-du-Sud", region: "Corse" },
  { departement: "2B - Haute-Corse", region: "Corse" },
  { departement: "30 - Gard", region: "Occitanie" },
  { departement: "31 - Haute-Garonne", region: "Occitanie" },
  { departement: "32 - Gers", region: "Occitanie" },
  { departement: "33 - Gironde", region: "Nouvelle-Aquitaine" },
  { departement: "34 - Hérault", region: "Occitanie" },
  { departement: "35 - Ille-et-Vilaine", region: "Bretagne" },
  { departement: "36 - Indre", region: "Centre-Val de Loire" },
  { departement: "37 - Indre-et-Loire", region: "Centre-Val de Loire" },
  { departement: "38 - Isère", region: "Auvergne-Rhône-Alpes" },
  { departement: "39 - Jura", region: "Bourgogne-Franche-Comté" },
  { departement: "40 - Landes", region: "Nouvelle-Aquitaine" },
  { departement: "41 - Loir-et-Cher", region: "Centre-Val de Loire" },
  { departement: "42 - Loire", region: "Auvergne-Rhône-Alpes" },
  { departement: "43 - Haute-Loire", region: "Auvergne-Rhône-Alpes" },
  { departement: "44 - Loire-Atlantique", region: "Pays de la Loire" },
  { departement: "45 - Loiret", region: "Centre-Val de Loire" },
  { departement: "46 - Lot", region: "Occitanie" },
  { departement: "47 - Lot-et-Garonne", region: "Nouvelle-Aquitaine" },
  { departement: "48 - Lozère", region: "Occitanie" },
  { departement: "49 - Maine-et-Loire", region: "Pays de la Loire" },
  { departement: "50 - Manche", region: "Normandie" },
  { departement: "51 - Marne", region: "Grand Est" },
  { departement: "52 - Haute-Marne", region: "Grand Est" },
  { departement: "53 - Mayenne", region: "Pays de la Loire" },
  { departement: "54 - Meurthe-et-Moselle", region: "Grand Est" },
  { departement: "55 - Meuse", region: "Grand Est" },
  { departement: "56 - Morbihan", region: "Bretagne" },
  { departement: "57 - Moselle", region: "Grand Est" },
  { departement: "58 - Nièvre", region: "Bourgogne-Franche-Comté" },
  { departement: "59 - Nord", region: "Hauts-de-France" },
  { departement: "60 - Oise", region: "Hauts-de-France" },
  { departement: "61 - Orne", region: "Normandie" },
  { departement: "62 - Pas-de-Calais", region: "Hauts-de-France" },
  { departement: "63 - Puy-de-Dôme", region: "Auvergne-Rhône-Alpes" },
  { departement: "64 - Pyrénées-Atlantiques", region: "Nouvelle-Aquitaine" },
  { departement: "65 - Hautes-Pyrénées", region: "Occitanie" },
  { departement: "66 - Pyrénées-Orientales", region: "Occitanie" },
  { departement: "67 - Bas-Rhin", region: "Grand Est" },
  { departement: "68 - Haut-Rhin", region: "Grand Est" },
  { departement: "69 - Rhône", region: "Auvergne-Rhône-Alpes" },
  { departement: "70 - Haute-Saône", region: "Bourgogne-Franche-Comté" },
  { departement: "71 - Saône-et-Loire", region: "Bourgogne-Franche-Comté" },
  { departement: "72 - Sarthe", region: "Pays de la Loire" },
  { departement: "73 - Savoie", region: "Auvergne-Rhône-Alpes" },
  { departement: "74 - Haute-Savoie", region: "Auvergne-Rhône-Alpes" },
  { departement: "75 - Paris", region: "Île-de-France" },
  { departement: "76 - Seine-Maritime", region: "Normandie" },
  { departement: "77 - Seine-et-Marne", region: "Île-de-France" },
  { departement: "78 - Yvelines", region: "Île-de-France" },
  { departement: "79 - Deux-Sèvres", region: "Nouvelle-Aquitaine" },
  { departement: "80 - Somme", region: "Hauts-de-France" },
  { departement: "81 - Tarn", region: "Occitanie" },
  { departement: "82 - Tarn-et-Garonne", region: "Occitanie" },
  { departement: "83 - Var", region: "Provence-Alpes-Côte d'Azur" },
  { departement: "84 - Vaucluse", region: "Provence-Alpes-Côte d'Azur" },
  { departement: "85 - Vendée", region: "Pays de la Loire" },
  { departement: "86 - Vienne", region: "Nouvelle-Aquitaine" },
  { departement: "87 - Haute-Vienne", region: "Nouvelle-Aquitaine" },
  { departement: "88 - Vosges", region: "Grand Est" },
  { departement: "89 - Yonne", region: "Bourgogne-Franche-Comté" },
  {
    departement: "90 - Territoire de Belfort",
    region: "Bourgogne-Franche-Comté",
  },
  { departement: "91 - Essonne", region: "Île-de-France" },
  { departement: "92 - Hauts-de-Seine", region: "Île-de-France" },
  { departement: "93 - Seine-Saint-Denis", region: "Île-de-France" },
  { departement: "94 - Val-de-Marne", region: "Île-de-France" },
  { departement: "95 - Val-d'Oise", region: "Île-de-France" },
  { departement: "971 - Guadeloupe", region: "Guadeloupe" },
  { departement: "972 - Martinique", region: "Martinique" },
  { departement: "973 - Guyane", region: "Guyane" },
  { departement: "974 - La Réunion", region: "La Réunion" },
  { departement: "976 - Mayotte", region: "Mayotte" },
];
