export const FETCH_USER_CONTRIBUTIONS = "FETCH_USER_CONTRIBUTIONS";
export const SET_USER_CONTRIBUTIONS = "SET_USER_CONTRIBUTIONS";
export const UPDATE_USER_CONTRIBUTIONS = "UPDATE_USER_CONTRIBUTIONS";
export const DELETE_DISPOSITIF = "DELETE_DISPOSITIF";
