export const VOICEOVER_ADD_ITEM = "VOICEOVER_ADD_ITEM";
export const VOICEOVER_REMOVE_ITEM = "VOICEOVER_REMOVE_ITEM";
export const VOICEOVER_UPDATE_SCROLL = "VOICEOVER_UPDATE_SCROLL";
export const VOICEOVER_SET_READING_ITEM = "VOICEOVER_SET_READING_ITEM";
export const VOICEOVER_SHOULD_STOP = "VOICEOVER_SHOULD_STOP";
