steps:
  # Get the secrets
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: bash
    args:
      [
        "-c",
        'for secret in $(gcloud secrets list --filter=REACT --format=''value(NAME)''); do echo NEXT_PUBLIC_$secret="$(gcloud secrets versions access --secret=$secret latest)" >> cloudbuild.env; done',
      ]
    dir: apps/client

  # Build the front image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:latest",
        "--build-arg",
        "APP_SERVER_URL=${_APP_SERVER_URL}",
        "--build-arg",
        "APP_ENV=${_APP_ENV}",
        "--build-arg",
        "APP_SITE_URL=${_APP_SITE_URL}",
        "-f",
        "./apps/client/Dockerfile",
        ".",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        # Use array for optional command-line arguments (Google Shell Style Guide)
        # https://google.github.io/styleguide/shellguide.html#arrays
        vpc_args=()
        if [[ -n "${_VPC_CONNECTOR}" ]]; then
          vpc_args=(--vpc-connector="${_VPC_CONNECTOR}")
        fi

        gcloud run deploy ${_COMPONENT}-${_ENV} \
          --allow-unauthenticated \
          --concurrency 160 \
          --image ${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_COMPONENT}:$SHORT_SHA \
          --max-instances ${_MAX_INSTANCES} \
          --memory ${_MEMORY} \
          --platform managed \
          --port 3000 \
          --project $PROJECT_ID \
          --region ${_REGION} \
          --service-account ${_SA} \
          --set-secrets MONGODB_URI=${_MONGODB_VAR}:latest \
          --set-env-vars DISABLE_SEARCH_COUNTS=${_DISABLE_SEARCH_COUNTS} \
          "${vpc_args[@]}"

options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_32"

substitutions:
  _MAX_INSTANCES: "20"
  _COMPONENT: frontend
  _REGION: europe-west1
  _REGISTRY: "registry-${_ENV}"
  _REGISTRY_URL: "${_REGION}-docker.pkg.dev"
  _DISABLE_SEARCH_COUNTS: "false"

timeout: 1200s
