import type { ThemeState } from "~/services/redux/Themes/themes.reducer";

// Helper function to ensure all themes have the required gradientColors property
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const ensureGradientColors = (themes: any[]) => {
  return themes.map((theme) => ({
    ...theme,
    gradientColors: theme.gradientColors || {
      colorTop: theme.colors.color100,
      colorBottom: theme.colors.color80,
    },
  }));
};

// Original theme data
const originalThemesData = [
  {
    _id: "63286a015d31b2c0cad9960a",
    name: {
      fr: "apprendre le français",
      en: "learn French",
      ar: "تعلّم الفرنسيّة",
      fa: "آموختن زبان فرانسوی",
      ps: "فرانسوي زده کړئ",
      ru: "учить французский",
      uk: "Курси французької мови",
      ti: "ትምህርቲ ቓንቓ ፈርንሳይ ምምሃር",
    },
    short: {
      fr: "Français",
      en: "French",
      ar: "الفرنسيّة",
      fa: "فرانسوی",
      ps: "فرانسوی",
      ru: "Французский",
      uk: "Французька мова",
      ti: "ፈረንሳይ",
    },
    mainColor: "#BFCCFB",
    colors: {
      color100: "#3D2884",
      color80: "#705FA4",
      color60: "#A396C4",
      color40: "#D6CDE4",
      color30: "#EFE8F4",
    },
    position: 2,
    icon: {
      secure_url: "/images/icon_elearning.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Français.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/francais.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/francais.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-francais.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/français.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/français.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "🇫🇷",
    active: true,
  },
  {
    _id: "63450dd43e23cd7181ba0b26",
    name: {
      fr: "famille",
      uk: "Сім‘я",
      ps: " کورنۍ",
      fa: " خانواده",
      ti: " ስድራ-ቤት",
      en: "Family",
      ru: "Семья",
      ar: "العائلة",
    },
    short: {
      fr: "Famille",
      uk: "Сім‘я",
      ps: " کورنۍ",
      fa: " خانواده",
      ti: " ስድራ-ቤት",
      en: "Family",
      ru: "Семья",
      ar: "العائلة",
    },
    mainColor: "#FBB8F6",
    colors: {
      color100: "#77057A",
      color80: "#9E2DAD",
      color60: "#D16DEA",
      color40: "#DB8EEF",
      color30: "#F9F1FD",
    },
    position: 8,
    icon: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1665471801/pictures/o1fsbcdgsktlohgqnagp.svg",
      public_id: "pictures/o1fsbcdgsktlohgqnagp",
      imgId: "6345153bf14a373d5af28d55",
    },
    banner: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1665469779/pictures/gfgzz4tcbxpe6edz2scu.svg",
      public_id: "pictures/gfgzz4tcbxpe6edz2scu",
      imgId: "63450d553e23cd7181ba0aef",
    },
    appBanner: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1665469793/pictures/vqzsfmw8o7fgcjnbf07m.png",
      public_id: "pictures/vqzsfmw8o7fgcjnbf07m",
      imgId: "63450d623e23cd7181ba0af1",
    },
    appImage: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1665469805/pictures/zhsms7ptlkjvolprxi3z.svg",
      public_id: "pictures/zhsms7ptlkjvolprxi3z",
      imgId: "63450d6f3e23cd7181ba0aff",
    },
    shareImage: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1665469825/pictures/fpjeqa0oxl8rp2uelrbz.png",
      public_id: "pictures/fpjeqa0oxl8rp2uelrbz",
      imgId: "63450d813e23cd7181ba0b01",
    },
    dispositifImage: {
      secure_url: "https://cards/dispositif/famille.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "https://cards/demarche/famille.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "👨‍👩‍👦",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad9960d",
    name: {
      fr: "me déplacer",
      en: "move about",
      ar: "التنقّل",
      fa: "سفر کردن",
      ps: "تقل او حرکت",
      ru: "перемещаться",
      uk: "Транспорт",
      ti: "ኣነ ክሳፈር \\ ይጉዓዝ",
    },
    short: {
      fr: "Mobilité",
      en: "Mobility",
      ar: "التنقّل",
      fa: "تحرک",
      ps: "خوځښت",
      ru: "Мобильность",
      uk: "Транспорт",
      ti: "ብቅዓት = ክእለት",
    },
    mainColor: "#FCC0B0",
    colors: {
      color100: "#CD5605",
      color80: "#F97319",
      color60: "#FB9B5A",
      color40: "#FDD7BD",
      color30: "#FEEBDE",
    },
    position: 7,
    icon: {
      secure_url: "/images/icon_bus.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Mobilité.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/transport.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/transport.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-mobilite.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/mobilité.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/mobilité.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "🚗",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad9960e",
    name: {
      fr: "trouver un travail",
      en: "find a job",
      ar: "ايجاد عمل",
      fa: "پیدا کردن شغل",
      ps: "دنده ومومئ",
      ru: "найти работу",
      uk: "Працевлаштування",
      ti: "ሓደ ስራሕ ምርካብ",
    },
    short: {
      fr: "Insertion pro",
      en: "Job hunting",
      ar: "الاندماج المهني",
      fa: "درج حرفه ای",
      ps: "مسلکي مرسته",
      ru: "Работа",
      uk: "Працевлаштування",
      ti: "ምትእትታው ሞያ ብውሕልልነት",
    },
    mainColor: "#60E0EB",
    colors: {
      color100: "#055E5A",
      color80: "#27A8A5",
      color60: "#82F2DB",
      color40: "#D7FAF2",
      color30: "#EDFDF9",
    },
    position: 6,
    icon: {
      secure_url: "/images/icon_briefcase.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Insertion-pro.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/travail.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/travail.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-insertion.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/travail.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/travail.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "💼",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad9960b",
    name: {
      fr: "gérer mes papiers",
      en: "manage my paperwork",
      ar: "إدارة أوراقي",
      fa: "مدیریت پرونده هایم",
      ps: "خپلې اسناد تنظیم کړئ",
      ru: "разобраться с документами",
      uk: "мої документи",
      ti: "ባዕለይ የሳልጥ  ወረቃቕተይ",
    },
    short: {
      fr: "Administratif",
      en: "Admin",
      ar: "المعاملات الاداريّة",
      fa: "اداری",
      ps: "اداري",
      ru: "Административное",
      uk: "Адміністративні питання",
      ti: "ቤት ጽሕፈታት",
    },
    mainColor: "#EAC7B2",
    colors: {
      color100: "#443023",
      color80: "#715F56",
      color60: "#9D8F88",
      color40: "#CABEBB",
      color30: "#EEE7E5",
    },
    position: 1,
    icon: {
      secure_url: "/images/icon_office.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Administratif.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/admin.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/admin.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-administratif.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/administratif.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/administratif.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "📝",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad99611",
    name: {
      fr: "faire des études",
      en: "study",
      ar: "الدّراسة",
      fa: "شروع کردن تحصیل",
      ps: "زده کړې ترسره کړئ",
      ru: "учиться",
      uk: "Навчання",
      ti: "ትምህርቲ ምግባር",
    },
    short: {
      fr: "Études",
      en: "Studies",
      ar: "الدّراسة",
      fa: "تحصیلات",
      ps: "زده کړې",
      ru: "Учеба",
      uk: "Навчання",
      ti: "ምምሃር",
    },
    mainColor: "#95E257",
    colors: {
      color100: "#204F01",
      color80: "#47AA0A",
      color60: "#70CE33",
      color40: "#DFFDAD",
      color30: "#F2F9E5",
    },
    position: 9,
    icon: {
      secure_url: "/images/icon_glasses.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Études.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/etudes.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/etudes.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-etudes.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/études.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/études.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "🎓",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad9960c",
    name: {
      fr: "me loger",
      en: "find housing",
      ar: "إيجاد سكن",
      fa: "پیدا کردن جای سکونت",
      ps: "استوګنځای پیداکړئ",
      ru: "найти жилье",
      uk: "Житло",
      ti: "ክነብር",
    },
    short: {
      fr: "Logement",
      en: "Housing",
      ar: "إسكان",
      fa: "مسکن",
      ps: "استوګنځای",
      ru: "Жилье",
      uk: "Житло",
      ti: "መንበሪ ገዛ",
    },
    mainColor: "#B6CFFB",
    colors: {
      color100: "#06508C",
      color80: "#1E9ED1",
      color60: "#88C6E3",
      color40: "#C1E3F2",
      color30: "#DDF2F9",
    },
    position: 3,
    icon: {
      secure_url: "/images/icon_house.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Logement.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/logement.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/logement.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-logement.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/logement.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/logement.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "🏡",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad9960f",
    name: {
      fr: "me soigner",
      en: "get medical care",
      ar: "العناية الصحّية",
      fa: "درمان",
      ps: "خپله درملنه وکړئ",
      ru: "получить медицинскую помощь",
      uk: "Медичні послуги",
      ti: "ኣነ ክሕከም",
    },
    short: {
      fr: "Santé",
      en: "Health",
      ar: "الصحّة",
      fa: "صحت",
      ps: "روغتیا",
      ru: "Здоровье",
      uk: "Охорона здоров'я",
      ti: "ጥዕና",
    },
    mainColor: "#FCC0B4",
    colors: {
      color100: "#910940",
      color80: "#D64B71",
      color60: "#E78CA2",
      color40: "#F7CDD4",
      color30: "#FFEDED",
    },
    position: 4,
    icon: {
      secure_url: "/images/icon_heartBeat.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Santé.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/sante.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/sante.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-sante.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/santé.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/santé.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "👨‍⚕️",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad99610",
    name: {
      fr: "apprendre un métier",
      en: "learn a job",
      ar: "تعلم مهنة",
      fa: "آموختن یک کسب",
      ps: "یو کسب زده کړئ",
      ru: "получить профессию",
      uk: "Професійна підготовка",
      ti: "ሓደ ሞያ ምምሃር",
    },
    short: {
      fr: "Formation pro",
      en: "Professional training",
      ar: "التدريب المهني",
      fa: "آموزش حرفه ای",
      ps: "مسلکي روزنه",
      ru: "Профессиональная подготовка",
      uk: "Професійна освіта",
      ti: "ምስልጣን ሞያ",
    },
    mainColor: "#E2CF58",
    colors: {
      color100: "#095411",
      color80: "#26B759",
      color60: "#82E59B",
      color40: "#D4F4D7",
      color30: "#E8F4E8",
    },
    position: 5,
    icon: {
      secure_url: "/images/icon_measure.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Formation-pro.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/metier.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/metier.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-formation-pro.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/formation.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/formation.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "👩🏼‍🏫",
    active: true,
  },
  {
    _id: "63286a015d31b2c0cad99614",
    name: {
      fr: "occuper mon temps libre",
      en: "occupy my free time",
      ar: "إشغال وقت فراغي",
      fa: "مشغول شدن در اوقات بیکار",
      ps: "خپل اضافی او فارغ وخت ډک کړئ",
      ru: "занять свободное время",
      uk: "Вільний час",
      ti: "ኣብ ትርፊ ግዘይ መደብ ምሓዝ",
    },
    short: {
      fr: "Loisir",
      en: "Leisure",
      ar: "التّسلية",
      fa: "سرگرمی ها",
      ps: "تفریح",
      ru: "Досуг",
      uk: "Відпочинок",
      ti: "ምዝንጋዕ",
    },
    mainColor: "#FFFFFF",
    colors: {
      color100: "#600566",
      color80: "#9E2DAD",
      color60: "#D16DEA",
      color40: "#EDC4FC",
      color30: "#F9F1FD",
    },
    position: 12,
    icon: {
      secure_url: "/images/icon_soccer.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Loisir.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/loisirs.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/loisirs.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-loisirs.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/loisirs.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/loisirs.svg",
      public_id: "",
      imgId: "",
    },
    notificationEmoji: "⚽",
    active: true,
  },
];

// Export the themes with guaranteed gradientColors property
export const mockedThemesData: ThemeState = ensureGradientColors(originalThemesData);
