# this docker file is not used, we don't user docker in dev for the moment (issue acces mongodb)

# Instructions:
# /!\ This dockerfile should be use for local tests purposes only!



# Use a node 12 base image
ARG NODE_VERSION=12
FROM node:${NODE_VERSION}-alpine

# Useful in order to execute the entrypoint script that will:
# - source all environment variables
# - start npm app
RUN apk update && apk add bash && rm -rf /var/cache/apk/*

WORKDIR /usr/src/app

# Copy package.json and install node modules
COPY package.json .
RUN npm install

# Add app source code
ADD . /usr/src/app

# Build app
RUN npm run tsc

# Copy environment variables.env file that you have to create in karfur/server/
COPY variables.env .

# Source environment variables and start app
ENTRYPOINT ["bash", "-c", "source variables.env && npm run start"]
