export const SET_ACTIVE_DISPOSITIFS = "SET_ACTIVE_DISPOSITIFS";
export const FETCH_ACTIVE_DISPOSITIFS = "FETCH_ACTIVE_DISPOSITIFS";
export const UPDATE_DISPOSITIF_REACTION = "UPDATE_DISPOSITIF_REACTION";
