export const SET_USER_HAS_SEEN_ONBOARDING = "SET_USER_HAS_SEEN_ONBOARDING";
export const SAVE_USER_HAS_SEEN_ONBOARDING = "SAVE_USER_HAS_SEEN_ONBOARDING";
export const SET_SELECTED_LANGUAGE = "SET_SELECTED_LANGUAGE";
export const SAVE_SELECTED_LANGUAGE = "SAVE_SELECTED_LANGUAGE";
export const SET_CURRENT_LANGUAGE = "SET_CURRENT_LANGUAGE";
export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SAVE_USER_LOCATION = "SAVE_USER_LOCATION";
export const SET_USER_AGE = "SET_USER_AGE";
export const SAVE_USER_AGE = "SAVE_USER_AGE";
export const SET_USER_FRENCH_LEVEL = "SET_USER_FRENCH_LEVEL";
export const SAVE_USER_FRENCH_LEVEL = "SAVE_USER_FRENCH_LEVEL";
export const GET_USER_INFOS = "GET_USER_INFOS";

export const REMOVE_USER_HAS_SEEN_ONBOARDING =
  "REMOVE_USER_HAS_SEEN_ONBOARDING";
export const REMOVE_SELECTED_LANGUAGE = "REMOVE_SELECTED_LANGUAGE";
export const REMOVE_USER_LOCATION = "REMOVE_USER_LOCATION";
export const REMOVE_USER_AGE = "REMOVE_USER_AGE";
export const REMOVE_USER_FRENCH_LEVEL = "REMOVE_USER_FRENCH_LEVEL";

export const SET_USER_FAVORITES = "SET_USER_FAVORITES";
export const ADD_USER_FAVORITE = "ADD_USER_FAVORITE";
export const REMOVE_USER_FAVORITE = "REMOVE_USER_FAVORITE";
export const REMOVE_USER_ALL_FAVORITES = "REMOVE_USER_ALL_FAVORITES";
