export const SET_RESULTS = "SET_RESULTS";
export const SET_NO_RESULTS = "SET_NO_RESULTS";
export const ADD_TO_QUERY = "ADD_TO_QUERY";
export const SET_INPUT_FOCUSED = "SET_INPUT_FOCUSED";

// Server-side search actions
export const FETCH_SEARCH_RESULTS_REQUEST = "FETCH_SEARCH_RESULTS_REQUEST";
export const FETCH_SEARCH_RESULTS_NEXT_PAGE = "FETCH_SEARCH_RESULTS_NEXT_PAGE";
export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";
export const APPEND_SEARCH_RESULTS = "APPEND_SEARCH_RESULTS";
export const FETCH_SEARCH_RESULTS_FAILURE = "FETCH_SEARCH_RESULTS_FAILURE";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
