export const SET_USER_HAS_SEEN_ONBOARDING = "SET_USER_HAS_SEEN_ONBOARDING";
export const SAVE_USER_HAS_SEEN_ONBOARDING = "SAVE_USER_HAS_SEEN_ONBOARDING";
export const SET_SELECTED_LANGUAGE = "SET_SELECTED_LANGUAGE";
export const SAVE_SELECTED_LANGUAGE = "SAVE_SELECTED_LANGUAGE";
