export const activities = [
  { tag: "Français", activity: "Sessions de certification FLE" },
  { tag: "Français", activity: "Cours de français" },
  { tag: "Français", activity: "Support d'auto-apprentissage" },
  { tag: "Français", activity: "Ateliers socio-linguistique" },
  // { tag: "Français", activity: "Évaluation et orientation" },
  { tag: "Logement", activity: "Hébergement citoyen" },
  { tag: "Logement", activity: "Hébergement longue durée" },
  // { tag: "Logement", activity: "Intermédiation locative" },
  { tag: "Logement", activity: "Centre d'hébergement" },
  { tag: "Logement", activity: "Accompagnement vers et dans le logement" },
  { tag: "Logement", activity: "Résidence sociale" },
  { tag: "Logement", activity: "Colocation solidaire" },
  { tag: "Logement", activity: "Parrainage" },
  { tag: "Administratif", activity: "Accompagnement global" },
  { tag: "Administratif", activity: "Interprétariat" },
  { tag: "Administratif", activity: "Accueil des mineurs" },
  { tag: "Administratif", activity: "Domiciliation postale" },
  // { tag: "Insertion pro", activity: "Insertion par l'activité économique" },
  { tag: "Insertion pro", activity: "Accompagnement vers l'emploi" },
  { tag: "Insertion pro", activity: "Mise en relation" },
  { tag: "Insertion pro", activity: "Coaching / Suivi dans l'emploi" },
  { tag: "Insertion pro", activity: "Bilan et définition du projet" },
  { tag: "Mobilité", activity: "Aides financières" },
  { tag: "Mobilité", activity: "Cours de conduite" },
  { tag: "Mobilité", activity: "Formation au code" },
  { tag: "Formation pro", activity: "Formations certifiantes" },
  { tag: "Formation pro", activity: "Formations non certifiantes" },
  { tag: "Formation pro", activity: "Apprentissage" },
  { tag: "Formation pro", activity: "Alternance" },
  { tag: "Études", activity: "Diplôme Universitaire Passerelle" },
  { tag: "Études", activity: "Formation initiale" },
  { tag: "Études", activity: "Formation continue" },
  { tag: "Études", activity: "Auto-apprentissage (MOOC)" },
  { tag: "Études", activity: "Formations civiques" },
  { tag: "Santé", activity: "Bilan de santé" },
  { tag: "Santé", activity: "Parcours de soin" },
  { tag: "Santé", activity: "Accompagnement psychologique" },
  { tag: "Loisir", activity: "Activités manuelles" },
  { tag: "Loisir", activity: "Tournois sportifs" },
  { tag: "Culture", activity: "Visite de la ville" },
  { tag: "Culture", activity: "Cours d'histoire de France" },
  { tag: "Bénévolat", activity: "Service civique pour français" },
  { tag: "Bénévolat", activity: "Service civique pour réfugiés" },
  { tag: "Bénévolat", activity: "Missions ponctuelles" },
  { tag: "Rencontre", activity: "Parrainage" },
];
