export const TOGGLE_LANGUE = "TOGGLE_LANGUE";
export const TOGGLE_LANG_MODAL = "TOGGLE_LANG_MODAL";

export const TOGGLE_TTS = "TOGGLE_TTS";
export const TOGGLE_SPINNER = "TOGGLE_SPINNER";

export const SET_LANGUES = "SET_LANGUES";
export const SET_DISPOSITIFS = "SET_DISPOSITIFS";
export const SET_STRUCTURES = "SET_STRUCTURES";

export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
