export const events = {
  REACHED_END_CONTENT: "REACHED_END_CONTENT",
  LANGUAGE_VALIDATE: "LANGUAGE_VALIDATE",
  LOCATION_VALIDATE: "LOCATION_VALIDATE",
  AGE_VALIDATE: "AGE_VALIDATE",
  FRENCH_LEVEL_VALIDATE: "FRENCH_LEVEL_VALIDATE",
  PROFILE_COMPLETED: "PROFILE_COMPLETED",
  PROFILE_NOT_COMPLETED: "PROFILE_NOT_COMPLETED",
};
