import type { Id } from "@refugies-info/api-types";

// Helper function to ensure all themes have the required gradientColors property
const ensureGradientColors = (themes: any[]) => {
  return themes.map((theme) => ({
    ...theme,
    gradientColors: theme.gradientColors || {
      colorTop: theme.colors.color100,
      colorBottom: theme.colors.color80,
    },
  }));
};

// Original theme data
const originalThemesMock = [
  {
    mainColor: "#BFCCFB",
    colors: {
      color100: "#3D2884",
      color80: "#705FA4",
      color60: "#A396C4",
      color40: "#D6CDE4",
      color30: "#EFE8F4",
    },
    gradientColors: {
      colorTop: "#3D2884",
      colorBottom: "#705FA4",
    },
    icon: {
      secure_url: "/images/icon_elearning.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Français.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/francais.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/francais.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-francais.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/français.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/français.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7df5" as Id,
    name: {
      fr: "apprendre le français",
      en: "learn French",
      ar: "تعلّم الفرنسيّة",
      fa: "آموختن زبان فرانسوی",
      ps: "فرانسوي زده کړئ",
      ru: "учить французский",
      uk: "Курси французької мови",
      ti: "ትምህርቲ ቓንቓ ፈርንሳይ ምምሃር",
    },
    short: {
      fr: "Français",
      en: "French",
      ar: "الفرنسيّة",
      fa: "فرانسوی",
      ps: "فرانسوی",
      ru: "Французский",
      uk: "Французька мова",
      ti: "ፈረንሳይ",
    },
    position: 2,
    notificationEmoji: "🇫🇷",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#EAC7B2",
    colors: {
      color100: "#443023",
      color80: "#715F56",
      color60: "#9D8F88",
      color40: "#CABEBB",
      color30: "#EEE7E5",
    },
    gradientColors: {
      colorTop: "#443023",
      colorBottom: "#715F56",
    },
    icon: {
      secure_url: "/images/icon_office.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Administratif.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/admin.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/admin.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-administratif.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/administratif.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/administratif.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7df6" as Id,
    name: {
      fr: "gérer mes papiers",
      en: "manage my paperwork",
      ar: "إدارة أوراقي",
      fa: "مدیریت پرونده هایم",
      ps: "خپلې اسناد تنظیم کړئ",
      ru: "разобраться с документами",
      uk: "мої документи",
      ti: "ባዕለይ የሳልጥ  ወረቃቕተይ",
    },
    short: {
      fr: "Administratif",
      en: "Admin",
      ar: "المعاملات الاداريّة",
      fa: "اداری",
      ps: "اداري",
      ru: "Административное",
      uk: "Адміністративні питання",
      ti: "ቤት ጽሕፈታት",
    },
    position: 1,
    notificationEmoji: "📝",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#B6CFFB",
    colors: {
      color100: "#06508C",
      color80: "#1E9ED1",
      color60: "#88C6E3",
      color40: "#C1E3F2",
      color30: "#DDF2F9",
    },
    gradientColors: {
      colorTop: "#06508C",
      colorBottom: "#1E9ED1",
    },
    icon: {
      secure_url: "/images/icon_house.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Logement.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/logement.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/logement.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-logement.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/logement.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/logement.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7df7" as Id,
    name: {
      fr: "me loger",
      en: "find housing",
      ar: "إيجاد سكن",
      fa: "پیدا کردن جای سکونت",
      ps: "استوګنځای پیداکړئ",
      ru: "найти жилье",
      uk: "Житло",
      ti: "ክነብር",
    },
    short: {
      fr: "Logement",
      en: "Housing",
      ar: "إسكان",
      fa: "مسکن",
      ps: "استوګنځای",
      ru: "Жилье",
      uk: "Житло",
      ti: "መንበሪ ገዛ",
    },
    position: 5,
    notificationEmoji: "🏡",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#FCC0B0",
    colors: {
      color100: "#CD5605",
      color80: "#F97319",
      color60: "#FB9B5A",
      color40: "#FDD7BD",
      color30: "#FEEBDE",
    },
    icon: {
      secure_url: "/images/icon_bus.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Mobilité.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/transport.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/transport.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-mobilite.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/mobilité.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/mobilité.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7df8" as Id,
    name: {
      fr: "me déplacer",
      en: "move about",
      ar: "التنقّل",
      fa: "سفر کردن",
      ps: "تقل او حرکت",
      ru: "перемещаться",
      uk: "Транспорт",
      ti: "ኣነ ክሳፈር \\ ይጉዓዝ",
    },
    short: {
      fr: "Mobilité",
      en: "Mobility",
      ar: "التنقّل",
      fa: "تحرک",
      ps: "خوځښت",
      ru: "Мобильность",
      uk: "Транспорт",
      ti: "ብቅዓት = ክእለት",
    },
    position: 7,
    notificationEmoji: "🚗",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#60E0EB",
    colors: {
      color100: "#055E5A",
      color80: "#27A8A5",
      color60: "#82F2DB",
      color40: "#D7FAF2",
      color30: "#EDFDF9",
    },
    gradientColors: {
      colorTop: "#055E5A",
      colorBottom: "#27A8A5",
    },
    icon: {
      secure_url: "/images/icon_briefcase.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Insertion-pro.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/travail.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/travail.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-insertion.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/travail.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/travail.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7df9" as Id,
    name: {
      fr: "trouver un travail",
      en: "find a job",
      ar: "ايجاد عمل",
      fa: "پیدا کردن شغل",
      ps: "دنده ومومئ",
      ru: "найти работу",
      uk: "Працевлаштування",
      ti: "ሓደ ስራሕ ምርካብ",
    },
    short: {
      fr: "Insertion pro",
      en: "Job hunting",
      ar: "الاندماج المهني",
      fa: "درج حرفه ای",
      ps: "مسلکي مرسته",
      ru: "Работа",
      uk: "Працевлаштування",
      ti: "ምትእትታው ሞያ ብውሕልልነት",
    },
    position: 4,
    notificationEmoji: "💼",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#FCC0B4",
    colors: {
      color100: "#910940",
      color80: "#D64B71",
      color60: "#E78CA2",
      color40: "#F7CDD4",
      color30: "#FFEDED",
    },
    icon: {
      secure_url: "/images/icon_heartBeat.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Santé.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/sante.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/sante.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-sante.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/santé.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/santé.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7dfa" as Id,
    name: {
      fr: "me soigner",
      en: "get medical care",
      ar: "العناية الصحّية",
      fa: "درمان",
      ps: "خپله درملنه وکړئ",
      ru: "получить медицинскую помощь",
      uk: "Медичні послуги",
      ti: "ኣነ ክሕከም",
    },
    short: {
      fr: "Santé",
      en: "Health",
      ar: "الصحّة",
      fa: "صحت",
      ps: "روغتیا",
      ru: "Здоровье",
      uk: "Охорона здоров'я",
      ti: "ጥዕና",
    },
    position: 6,
    notificationEmoji: "👨\u200d⚕️",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#E2CF58",
    colors: {
      color100: "#095411",
      color80: "#26B759",
      color60: "#82E59B",
      color40: "#D4F4D7",
      color30: "#E8F4E8",
    },
    gradientColors: {
      colorTop: "#095411",
      colorBottom: "#26B759",
    },
    icon: {
      secure_url: "/images/icon_measure.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Formation-pro.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/metier.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/metier.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-formation-pro.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/formation.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/dispositif/formation.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7dfb" as Id,
    name: {
      fr: "apprendre un métier",
      en: "learn a job",
      ar: "تعلم مهنة",
      fa: "آموختن یک کسب",
      ps: "یو کسب زده کړئ",
      ru: "получить профессию",
      uk: "Професійна підготовка",
      ti: "ሓደ ሞያ ምምሃር",
    },
    short: {
      fr: "Formation pro",
      en: "Professional training",
      ar: "التدريب المهني",
      fa: "آموزش حرفه ای",
      ps: "مسلکي روزنه",
      ru: "Профессиональная подготовка",
      uk: "Професійна освіта",
      ti: "ምስልጣን ሞያ",
    },
    position: 3,
    notificationEmoji: "👩🏼\u200d🏫",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#95E257",
    colors: {
      color100: "#204F01",
      color80: "#47AA0A",
      color60: "#70CE33",
      color40: "#DFFDAD",
      color30: "#F2F9E5",
    },
    icon: {
      secure_url: "/images/icon_glasses.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Études.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/etudes.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/etudes.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-etudes.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/études.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/études.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7dfc" as Id,
    name: {
      fr: "faire des études",
      en: "study",
      ar: "الدّراسة",
      fa: "شروع کردن تحصیل",
      ps: "زده کړې ترسره کړئ",
      ru: "учиться",
      uk: "Навчання",
      ti: "ትምህርቲ ምግባር",
    },
    short: {
      fr: "Études",
      en: "Studies",
      ar: "الدّراسة",
      fa: "تحصیلات",
      ps: "زده کړې",
      ru: "Учеба",
      uk: "Навчання",
      ti: "ምምሃር",
    },
    position: 9,
    notificationEmoji: "🎓",
    active: true,
    adminComments: "",
  },
  {
    mainColor: "#FFFFFF",
    colors: {
      color100: "#600566",
      color80: "#9E2DAD",
      color60: "#D16DEA",
      color40: "#EDC4FC",
      color30: "#F9F1FD",
    },
    gradientColors: {
      colorTop: "#600566",
      colorBottom: "#9E2DAD",
    },
    icon: {
      secure_url: "/images/icon_soccer.svg",
      public_id: "",
      imgId: "",
    },
    banner: {
      secure_url: "/images/illustration_Loisir.svg",
      public_id: "",
      imgId: "",
    },
    appBanner: {
      secure_url: "/images/app-banner/loisirs.png",
      public_id: "",
      imgId: "",
    },
    appImage: {
      secure_url: "/images/app/loisirs.svg",
      public_id: "",
      imgId: "",
    },
    shareImage: {
      secure_url: "/images/share/ri-loisirs.png",
      public_id: "",
      imgId: "",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/loisirs.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/loisirs.svg",
      public_id: "",
      imgId: "",
    },
    _id: "6319f6b363ab2bbb162d7dff" as Id,
    name: {
      fr: "occuper mon temps libre",
      en: "occupy my free time",
      ar: "إشغال وقت فراغي",
      fa: "مشغول شدن در اوقات بیکار",
      ps: "خپل اضافی او فارغ وخت ډک کړئ",
      ru: "занять свободное время",
      uk: "Вільний час",
      ti: "ኣብ ትርፊ ግዘይ መደብ ምሓዝ",
    },
    short: {
      fr: "Loisir",
      en: "Leisure",
      ar: "التّسلية",
      fa: "سرگرمی ها",
      ps: "تفریح",
      ru: "Досуг",
      uk: "Відпочинок",
      ti: "ምዝንጋዕ",
    },
    position: 11,
    notificationEmoji: "⚽",
    active: true,
    adminComments: "",
  },

  {
    mainColor: "#FBB8F6",
    colors: {
      color100: "#77057A",
      color80: "#9E2DAD",
      color60: "#D16DEA",
      color40: "#DB8EEF",
      color30: "#FDC4FC",
    },
    icon: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1663058487/pictures/o52hghafc04bexxedrik.svg",
      public_id: "pictures/o52hghafc04bexxedrik",
      imgId: "63204239dd70acd9199aed06",
    },
    banner: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1662990767/pictures/o1x9jwn7ncwx18mqcnx9.svg",
      public_id: "pictures/o1x9jwn7ncwx18mqcnx9",
      imgId: "631f39b068917b340a0411fe",
    },
    appBanner: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1662990785/pictures/ninp4ko4vbnrorsgyz7z.svg",
      public_id: "pictures/ninp4ko4vbnrorsgyz7z",
      imgId: "631f39c368917b340a041202",
    },
    appImage: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1662999880/pictures/ot6qwuszncts5ppxusds.svg",
      public_id: "pictures/ot6qwuszncts5ppxusds",
      imgId: "631f5d4ad449751db1492051",
    },
    shareImage: {
      secure_url:
        "https://res.cloudinary.com/dlmqnnhp6/image/upload/v1662995793/pictures/wndug5571lzvcs1sguc1.png",
      public_id: "pictures/wndug5571lzvcs1sguc1",
      imgId: "631f4d52d4047aca79ffd170",
    },
    dispositifImage: {
      secure_url: "/images/cards/dispositif/famille.svg",
      public_id: "",
      imgId: "",
    },
    demarcheImage: {
      secure_url: "/images/cards/demarche/famille.svg",
      public_id: "",
      imgId: "",
    },
    _id: "631f3bfe68917b340a04120c" as Id,
    name: {
      fr: "famille",
      uk: "Сім‘я",
      ps: "کورنۍ",
      fa: "خانواده",
      en: "Family",
      ti: "ስድራ-ቤት",
      ru: "Семья",
      ar: "العائلة",
    },
    short: {
      fr: "Famille",
      uk: "Сім‘я",
      ps: "کورنۍ",
      fa: "خانواده",
      en: "Family",
      ti: "ስድራ-ቤት",
      ru: "Семья",
      ar: "العائلة",
    },
    position: 14,
    notificationEmoji: "👨\u200d👩\u200d👦",
    created_at: "2022-09-12T14:02:38.447Z",
    updatedAt: "2022-09-13T08:41:38.952Z",
    __v: 0,
    active: true,
    adminComments: "",
  },
];

// Export the themes with guaranteed gradientColors property
export const activeThemesMock = ensureGradientColors(originalThemesMock);
