export const FETCH_SELECTED_DISPOSITIF = "FETCH_SELECTED_DISPOSITIF";
export const SET_SELECTED_DISPOSITIF = "SET_SELECTED_DISPOSITIF";
export const UPDATE_SELECTED_DISPOSITIF = "UPDATE_SELECTED_DISPOSITIF";
export const CLEAR_SELECTED_DISPOSITIF = "CLEAR_SELECTED_DISPOSITIF";
