exports.data = [
  {
    locale: "ar",
    langue: "Arabic (Egypt)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ar-EG, Hoda)",
  }, //Cas générique dupliqué
  {
    locale: "ar-EG",
    langue: "Arabic (Egypt)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ar-EG, Hoda)",
  },
  {
    locale: "ar-SA",
    langue: "Arabic (Saudi Arabia)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (ar-SA, Naayf)",
  },
  {
    locale: "bg-BG",
    langue: "Bulgarian",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (bg-BG, Ivan)",
  },
  {
    locale: "ca-ES",
    langue: "Catalan",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ca-ES, HerenaRUS)",
  },
  {
    locale: "cs-CZ",
    langue: "Czech",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (cs-CZ, Jakub)",
  },
  {
    locale: "da-DK",
    langue: "Danish",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (da-DK, HelleRUS)",
  },
  {
    locale: "de-AT",
    langue: "German (Austria)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (de-AT, Michael)",
  },
  {
    locale: "de-CH",
    langue: "German (Switzerland)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (de-CH, Karsten)",
  },
  {
    locale: "de-DE",
    langue: "German (Germany)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (de-DE, Hedda)",
  },
  {
    locale: "de-DE2",
    langue: "German (Germany)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (de-DE, HeddaRUS)",
  },
  {
    locale: "de-DE3",
    langue: "German (Germany)",
    gender: "Male",
    name:
      "Microsoft Server Speech Text to Speech Voice (de-DE, Stefan, Apollo)",
  },
  {
    locale: "el-GR",
    langue: "Greek",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (el-GR, Stefanos)",
  },
  {
    locale: "en-AU",
    langue: "English (Australia)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-AU, Catherine)",
  },
  {
    locale: "en-AU2",
    langue: "English (Australia)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-AU, HayleyRUS)",
  },
  {
    locale: "en-CA",
    langue: "English (Canada)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-CA, Linda)",
  },
  {
    locale: "en-CA2",
    langue: "English (Canada)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-CA, HeatherRUS)",
  },

  {
    locale: "en",
    langue: "English (UK)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-GB, Susan, Apollo)",
  }, //Cas générique dupliqué
  {
    locale: "en-GB",
    langue: "English (UK)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-GB, Susan, Apollo)",
  },
  {
    locale: "en-GB2",
    langue: "English (UK)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-GB, HazelRUS)",
  },
  {
    locale: "en-GB3",
    langue: "English (UK)",
    gender: "Male",
    name:
      "Microsoft Server Speech Text to Speech Voice (en-GB, George, Apollo)",
  },
  {
    locale: "en-IE",
    langue: "English (Ireland)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (en-IE, Sean)",
  },
  {
    locale: "en-IN",
    langue: "English (India)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-IN, Heera, Apollo)",
  },
  {
    locale: "en-IN2",
    langue: "English (India)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-IN, PriyaRUS)",
  },
  {
    locale: "en-IN3",
    langue: "English (India)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (en-IN, Ravi, Apollo)",
  },
  {
    locale: "en-US",
    langue: "English (US)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)",
  },
  {
    locale: "en-US2",
    langue: "English (US)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)",
  },
  {
    locale: "en-US3",
    langue: "English (US)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (en-US, BenjaminRUS)",
  },
  {
    locale: "en-US4",
    langue: "English (US)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)",
  },
  {
    locale: "en-US5",
    langue: "English (US)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (en-US, Guy24kRUS)",
  },
  {
    locale: "es-ES",
    langue: "Spanish (Spain)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (es-ES, Laura, Apollo)",
  },
  {
    locale: "es-ES2",
    langue: "Spanish (Spain)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (es-ES, HelenaRUS)",
  },
  {
    locale: "es-ES3",
    langue: "Spanish (Spain)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (es-ES, Pablo, Apollo)",
  },
  {
    locale: "es-MX",
    langue: "Spanish (Mexico)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (es-MX, HildaRUS)",
  },
  {
    locale: "es-MX2",
    langue: "Spanish (Mexico)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (es-MX, Raul, Apollo)",
  },
  {
    locale: "fi-FI",
    langue: "Finnish",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (fi-FI, HeidiRUS)",
  },
  {
    locale: "fr-CA",
    langue: "French (Canada)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (fr-CA, Caroline)",
  },
  {
    locale: "fr-CA2",
    langue: "French (Canada)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (fr-CA, HarmonieRUS)",
  },
  {
    locale: "fr-S",
    langue: "French (Switzerland)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (fr-CH, Guillaume)",
  },

  {
    locale: "fr",
    langue: "French (France)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (fr-FR, Julie, Apollo)",
  }, //Cas générique dupliqué
  {
    locale: "fr-FR",
    langue: "French (France)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (fr-FR, Julie, Apollo)",
  },
  {
    locale: "fr-FR2",
    langue: "French (France)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (fr-FR, HortenseRUS)",
  },
  {
    locale: "fr-FR3",
    langue: "French (France)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (fr-FR, Paul, Apollo)",
  },
  {
    locale: "he-IL",
    langue: "Hebrew (Israel)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (he-IL, Asaf)",
  },
  {
    locale: "hi-IN",
    langue: "Hindi (India)",
    gender: "Female",
    name:
      "Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana, Apollo)",
  },
  {
    locale: "hi-IN2",
    langue: "Hindi (India)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana)",
  },
  {
    locale: "hi-IN3",
    langue: "Hindi (India)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (hi-IN, Hemant)",
  },
  {
    locale: "hr-HR",
    langue: "Croatian",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (hr-HR, Matej)",
  },
  {
    locale: "hu-HU",
    langue: "Hungarian",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (hu-HU, Szabolcs)",
  },
  {
    locale: "id-ID",
    langue: "Indonesian",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (id-ID, Andika)",
  },
  {
    locale: "it-IT",
    langue: "Italian",
    gender: "Male",
    name:
      "Microsoft Server Speech Text to Speech Voice (it-IT, Cosimo, Apollo)",
  },
  {
    locale: "it-IT2",
    langue: "Italian",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (it-IT, LuciaRUS)",
  },
  {
    locale: "ja-JP",
    langue: "Japanese",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi, Apollo)",
  },
  {
    locale: "ja-JP2",
    langue: "Japanese",
    gender: "Male",
    name:
      "Microsoft Server Speech Text to Speech Voice (ja-JP, Ichiro, Apollo)",
  },
  {
    locale: "ja-JP3",
    langue: "Japanese",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ja-JP, HarukaRUS)",
  },
  {
    locale: "ko-KR",
    langue: "Korean",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ko-KR, HeamiRUS)",
  },
  {
    locale: "ms-MY",
    langue: "Malay",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (ms-MY, Rizwan)",
  },
  {
    locale: "nb-NO",
    langue: "Norwegian",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (nb-NO, HuldaRUS)",
  },
  {
    locale: "nl-NL",
    langue: "Dutch",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (nl-NL, HannaRUS)",
  },
  {
    locale: "pl-PL",
    langue: "Polish",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (pl-PL, PaulinaRUS)",
  },
  {
    locale: "pt-BR",
    langue: "Portuguese (Brazil)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (pt-BR, HeloisaRUS)",
  },
  {
    locale: "pt-BR2",
    langue: "Portuguese (Brazil)",
    gender: "Male",
    name:
      "Microsoft Server Speech Text to Speech Voice (pt-BR, Daniel, Apollo)",
  },
  {
    locale: "pt-PT",
    langue: "Portuguese (Portugal)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (pt-PT, HeliaRUS)",
  },
  {
    locale: "ro-RO",
    langue: "Romanian",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (ro-RO, Andrei)",
  },
  {
    locale: "ru",
    langue: "Russian",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ru-RU, Irina, Apollo)",
  },
  {
    locale: "ru-RU",
    langue: "Russian",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (ru-RU, Pavel, Apollo)",
  },
  {
    locale: "ru-RU3",
    langue: "Russian",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (ru-RU, EkaterinaRUS)",
  },
  {
    locale: "sk-SK",
    langue: "Slovak",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (sk-SK, Filip)",
  },
  {
    locale: "sl-SI",
    langue: "Slovenian",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (sl-SI, Lado)",
  },
  {
    locale: "sv-SE",
    langue: "Swedish",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (sv-SE, HedvigRUS)",
  },
  {
    locale: "ta-IN",
    langue: "Tamil (India)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (ta-IN, Valluvar)",
  },
  {
    locale: "te-IN",
    langue: "Telugu (India)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (te-IN, Chitra)",
  },
  {
    locale: "th-TH",
    langue: "Thai",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (th-TH, Pattara)",
  },
  {
    locale: "tr-TR",
    langue: "Turkish",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (tr-TR, SedaRUS)",
  },
  {
    locale: "uk-UA",
    langue: "Ukrainian",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (uk-UA, PolinaNeural)",
  },
  {
    locale: "uk",
    langue: "Ukrainian",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (uk-UA, PolinaNeural)",
  },//Cas générique dupliqué
  {
    locale: "vi-VN",
    langue: "Vietnamese",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (vi-VN, An)",
  },
  {
    locale: "zh-CN",
    langue: "Chinese (Mainland)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (zh-CN, HuihuiRUS)",
  },
  {
    locale: "zh-CN2",
    langue: "Chinese (Mainland)",
    gender: "Female",
    name:
      "Microsoft Server Speech Text to Speech Voice (zh-CN, Yaoyao, Apollo)",
  },
  {
    locale: "zh-CN3",
    langue: "Chinese (Mainland)",
    gender: "Male",
    name:
      "Microsoft Server Speech Text to Speech Voice (zh-CN, Kangkang, Apollo)",
  },
  {
    locale: "zh-HK",
    langue: "Chinese (Hong Kong)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (zh-HK, Tracy, Apollo)",
  },
  {
    locale: "zh-HK2",
    langue: "Chinese (Hong Kong)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (zh-HK, TracyRUS)",
  },
  {
    locale: "zh-HK3",
    langue: "Chinese (Hong Kong)",
    gender: "Male",
    name: "Microsoft Server Speech Text to Speech Voice (zh-HK, Danny, Apollo)",
  },
  {
    locale: "zh-TW",
    langue: "Chinese (Taiwan)",
    gender: "Female",
    name:
      "Microsoft Server Speech Text to Speech Voice (zh-TW, Yating, Apollo)",
  },
  {
    locale: "zh-TW2",
    langue: "Chinese (Taiwan)",
    gender: "Female",
    name: "Microsoft Server Speech Text to Speech Voice (zh-TW, HanHanRUS)",
  },
];
