export const SET_STRUCTURES = "SET_STRUCTURES";
export const FETCH_STRUCTURES = "FETCH_STRUCTURES";
export const SET_USER_STRUCTURE = "SET_USER_STRUCTURE";
export const FETCH_USER_STRUCTURE = "FETCH_USER_STRUCTURE";
export const UPDATE_USER_STRUCTURE = "UPDATE_USER_STRUCTURE";
