export const SET_SELECTED_STRUCTURE = "SET_SELECTED_STRUCTURE";
export const FETCH_SELECTED_STRUCTURE = "FETCH_SELECTED_STRUCTURE";
export const UPDATE_SELECTED_STRUCTURE = "UPDATE_SELECTED_STRUCTURE";
