name: Build Mobile Staging

permissions:
  contents: read

on:
  # We only want to run this workflow when a push is made to the
  # staging-mobile branch and the changes include a change to the
  # mobile app or the API types.
  push:
    branches:
      - staging-mobile
    paths:
      - pnpm-lock.yaml
      - package.json
      - .github/workflows/build_mobile_staging.yml
      - apps/mobile/**
      - packages/api-types/**
  workflow_dispatch:

jobs:
  update:
    name: Build Mobile Staging
    runs-on: ubuntu-latest
    environment: staging-mobile
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "22.14.0"

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          pnpm add -g turbo
          pnpm install --frozen-lockfile

      - name: Setup GCP service account key
        run: |
          mkdir -p credentials
          echo '${{ secrets.EXPO_SERVICE_ACCOUNT_KEY}}'  | base64 --decode > credentials/refugies-info-appkey.json

      - name: Build and update app on both platforms
        working-directory: ./apps/mobile
        run: eas build --platform all --profile staging --non-interactive --no-wait
