name: Checks

on:
  pull_request:
    branches-ignore:
      - master-mobile
      - master-frontend
      - master-backend
      - staging-mobile
      - staging-frontend
      - staging-backend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: |
          pnpm add -g turbo
          pnpm install --frozen-lockfile

      - name: Build UI Package
        run: turbo build --filter=@refugies-info/ui

      - name: Lint
        run: pnpm lint

      - name: Check Types and Test
        run: turbo check:types test
        env:
          NEXT_PUBLIC_REACT_APP_ENV: ${{ vars.NEXT_PUBLIC_REACT_APP_ENV }}
          NEXT_PUBLIC_REACT_APP_ALGOLIA_API_KEY: ${{ vars.NEXT_PUBLIC_REACT_APP_ALGOLIA_API_KEY }}
          NEXT_PUBLIC_REACT_APP_ALGOLIA_INDEX_STG: ${{ vars.NEXT_PUBLIC_REACT_APP_ALGOLIA_INDEX_STG }}
          JEST_WATCHMAN: "0"

      - name: Lint styles
        run: pnpm lint:style
