name: Checks

permissions:
  contents: read

on:
  pull_request:
    branches-ignore:
      - master-mobile
      - master-frontend
      - master-backend
      - staging-mobile
      - staging-frontend
      - staging-backend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.14.0"

      - name: Install Dependencies
        run: |
          pnpm add -g turbo
          pnpm install --frozen-lockfile

      - name: Build UI Package
        run: turbo build --filter=@refugies-info/ui

      - name: Lint and Check Types
        run: pnpm lint check:types

      - name: Test (except mobile for now because flaky)
        run: turbo test --filter=!@refugies-info/mobile
        env:
          NEXT_PUBLIC_REACT_APP_ENV: ${{ vars.NEXT_PUBLIC_REACT_APP_ENV }}
          NEXT_PUBLIC_REACT_APP_ALGOLIA_API_KEY: ${{ vars.NEXT_PUBLIC_REACT_APP_ALGOLIA_API_KEY }}
          NEXT_PUBLIC_REACT_APP_ALGOLIA_INDEX_STG: ${{ vars.NEXT_PUBLIC_REACT_APP_ALGOLIA_INDEX_STG }}
          JEST_WATCHMAN: "0"

      - name: Lint styles
        run: pnpm lint:style
