name: Checks

on:
  pull_request:
    branches-ignore:
      - master-frontend
      - master-backend
      - staging-frontend
      - staging-backend
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"

      - name: Install expected yarn version
        run: sudo npm install --force --global yarn@1.22.22

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint, Check Types and Test
        run: yarn turbo lint check-types test
