name: Chromatic

permissions:
  contents: read

on:
  push:
    branches:
      - staging-frontend
      - master-frontend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.14.0"

      - name: Install Dependencies
        run: |
          pnpm add -g turbo
          pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:storybook

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build
          workingDir: apps/storybook
