name: Tests CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - name: Install dependencies using lockfile
        run: yarn install --immutable

      - name: Run tests
        run: yarn run test
