name: Migrate Staging

on:
  pull_request:
    branches:
      - staging-mobile
      - staging-frontend
      - staging-backend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging-migrate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"

      - name: Install expected yarn version
        run: sudo npm install --force --global yarn@1.22.22

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint, Check Types and Test
        run: yarn migrate up
        env:
          MIGRATE_MONGO_URI: ${{ secrets.MIGRATE_MONGO_URI }}
