export const READING_PAUSE = "READING_PAUSE";
export const READING_RESUME = "READING_RESUME";
export const ADD_READING = "ADD_READING";
export const RESET_READING = "RESET_READING";
export const SCROLL_READING = "SCROLL_READING";
export const SET_READING_ITEM = "SET_READING_ITEM";
