export const VOICEOVER_ADD_ITEM = "VOICEOVER_ADD_ITEM";
export const VOICEOVER_RESET_LIST = "VOICEOVER_RESET_LIST";
export const VOICEOVER_UPDATE_SCROLL = "VOICEOVER_UPDATE_SCROLL";
export const VOICEOVER_SET_READING_ITEM = "VOICEOVER_SET_READING_ITEM";
export const VOICEOVER_NEW_LIST = "VOICEOVER_NEW_LIST";
export const VOICEOVER_SET_REF = "VOICEOVER_SET_REF";
